#!/usr/bin/env python3
from pathlib import Path

path = Path(__file__).resolve().parents[1] / "src/app/app.html"
text = path.read_text(encoding="utf-8")
start = text.index('  <section\n    id="printSheetRoot"')
end = text.index('  </section>\n  </div>\n\n  <div class="report-reading">', start)

D = "div"

new_lines = [
    "  <section",
    "    id=\"printSheetRoot\"",
    "    class=\"report-page\"",
    "    [class.print-sheet--preview]=\"printPreviewOpen\"",
    "    aria-label=\"列印版報告\"",
    "  >",
    "    <header class=\"report-header\">",
    f"      <{D} class=\"brand\">",
    f"        <{D} class=\"brand-title\">Rental Buddy</{D}>",
    f"        <{D} class=\"brand-subtitle\">看房分析報告 (InBody Style)</{D}>",
    f"      </{D}>",
    f"      <{D} class=\"property-info\">",
    f"        <{D} class=\"property-row\">",
    "          <span class=\"label\">房源名稱</span>",
    "          <span class=\"value\">{{ activeRecord.name }}</span>",
    f"        </{D}>",
    f"        <{D} class=\"property-row\">",
    "          <span class=\"label\">地址</span>",
    "          <span class=\"value\">{{ address || '未填寫' }}</span>",
    f"        </{D}>",
    f"        <{D} class=\"property-row\">",
    "          <span class=\"label\">月租金</span>",
    "          <span class=\"value\">{{ monthlyRent ? 'NT$ ' + monthlyRent : '未填寫' }}</span>",
    f"        </{D}>",
    f"        <{D} class=\"property-row\">",
    "          <span class=\"label\">格局</span>",
    "          <span class=\"value\">{{ printLayoutLine }}</span>",
    f"        </{D}>",
    f"        <{D} class=\"property-row\">",
    "          <span class=\"label\">坪數</span>",
    "          <span class=\"value\">{{ layoutAreaPing ? layoutAreaPing + ' 坪' : '未填寫' }}</span>",
    f"        </{D}>",
    f"        <{D} class=\"property-row\">",
    "          <span class=\"label\">更新時間</span>",
    "          <span class=\"value\">{{ activeRecord.updatedAt | date:'yyyy/MM/dd HH:mm' }}</span>",
    f"        </{D}>",
    f"      </{D}>",
    f"      <{D} class=\"score-box\">",
    f"        <{D} class=\"score-main\">{{ reportScore100 }}<span> / 100</span></{D}>",
    f"        <{D} class=\"score-grade red\">{{ reportGrade }}</{D}>",
    f"        <{D} class=\"score-risk\">{{ reportRiskLevelLabel }}</{D}>",
    f"      </{D}>",
    "    </header>",
    "",
    "    <section class=\"section section--overview\">",
    f"      <{D} class=\"section-title\"><span class=\"num\">1.</span> OVERVIEW 總覽</{D}>",
    f"      <{D} class=\"overview-content\">",
    f"        <{D} class=\"metric-card\">",
    f"          <{D} class=\"metric-label\">RENTAL SCORE™</{D}>",
    f"          <{D} class=\"metric-value\">{{ reportScore100 }}<span> / 100</span></{D}>",
    f"          <{D} class=\"score-bar\" aria-hidden=\"true\">",
    "            @for (slot of printScoreBarSlots; track slot) {",
    f"              <{D} [class.active]=\"slot <= printScoreBarActiveCount\"></{D}>",
    "            }",
    f"          </{D}>",
    f"        </{D}>",
    f"        <{D} class=\"metric-card\">",
    f"          <{D} class=\"metric-label\">等級</{D}>",
    f"          <{D} class=\"metric-value red\">{{ reportGrade }}</{D}>",
    f"        </{D}>",
    f"        <{D} class=\"metric-card\">",
    f"          <{D} class=\"metric-label\">已確認項目</{D}>",
    f"          <{D} class=\"metric-value\">{{ confirmedCount }}<span> / {{ totalCount }}</span></{D}>",
    f"        </{D}>",
    f"        <{D} class=\"metric-card\">",
    f"          <{D} class=\"metric-label\">待確認項目</{D}>",
    f"          <{D} class=\"metric-value\">{{ leftCount }}</{D}>",
    f"        </{D}>",
    f"        <{D} class=\"area-average\">",
    f"          <{D} class=\"metric-label\">同區域平均分數</{D}>",
    f"          <{D} class=\"metric-value\">{{ printCandidateAverageDisplay }}</{D}>",
    f"          <{D} class=\"small-text muted\">{{ printCandidateAverageSub }}</{D}>",
    f"        </{D}>",
    f"      </{D}>",
    "    </section>",
    "",
    "    <section class=\"section section--ai\">",
    f"      <{D} class=\"section-title\"><span class=\"num\">2.</span> AI 分析總結</{D}>",
    f"      <{D} class=\"ai-content\">",
    f"        <{D} class=\"ai-box\">",
    f"          <{D} class=\"ai-box-title\">整體結論</{D}>",
    f"          <{D} class=\"ai-result\">{{ displayReportConclusionTitle }}</{D}>",
    "          <p>{{ displayReportConclusionDescForPrint }}</p>",
    f"        </{D}>",
    f"        <{D} class=\"ai-box\">",
    f"          <{D} class=\"ai-box-title\">主要優勢</{D}>",
    "          <ul class=\"ai-list\">",
    "            @for (item of displayReportStrengthsForPrint; track item.title) {",
    "              <li>",
    "                <span class=\"ai-icon good\" aria-hidden=\"true\">✓</span>",
    "                <span><strong>{{ item.title }}</strong> {{ item.description }}</span>",
    "              </li>",
    "            }",
    "          </ul>",
    f"        </{D}>",
    f"        <{D} class=\"ai-box\">",
    f"          <{D} class=\"ai-box-title\">主要風險</{D}>",
    "          <ul class=\"ai-list\">",
    "            @for (item of displayReportRisksForPrint; track item.title) {",
    "              <li>",
    "                <span class=\"ai-icon risk\" aria-hidden=\"true\">!</span>",
    "                <span><strong>{{ item.title }}</strong> {{ item.description }}</span>",
    "              </li>",
    "            }",
    "          </ul>",
    f"        </{D}>",
    f"      </{D}>",
    "    </section>",
    "",
    "    <section class=\"section section--category\">",
    f"      <{D} class=\"section-title\"><span class=\"num\">3.</span> 五分類分析</{D}>",
    f"      <{D} class=\"category-content\">",
    f"        <{D} class=\"radar-area\">",
    "          <svg class=\"radar-svg\" viewBox=\"0 0 300 300\" aria-label=\"五分類雷達圖\">",
    "            <polygon [attr.points]=\"getRadarPointsAtRatio(0.25)\" fill=\"none\" stroke=\"rgba(0,0,0,0.10)\" stroke-width=\"1\" />",
    "            <polygon [attr.points]=\"getRadarPointsAtRatio(0.5)\" fill=\"none\" stroke=\"rgba(0,0,0,0.10)\" stroke-width=\"1\" />",
    "            <polygon [attr.points]=\"getRadarPointsAtRatio(0.75)\" fill=\"none\" stroke=\"rgba(0,0,0,0.10)\" stroke-width=\"1\" />",
    "            <polygon [attr.points]=\"getRadarPointsAtRatio(1)\" fill=\"none\" stroke=\"rgba(0,0,0,0.18)\" stroke-width=\"1.2\" />",
    "            @for (axisId of radarAxisIds; track axisId) {",
    "              <line [attr.x1]=\"radarCenter\" [attr.y1]=\"radarCenter\" [attr.x2]=\"getRadarAxisXEnd(axisId)\" [attr.y2]=\"getRadarAxisYEnd(axisId)\" stroke=\"rgba(0,0,0,0.12)\" stroke-width=\"1\" />",
    "              <text class=\"radar-label-text\" [attr.x]=\"getRadarAxisXLabel(axisId)\" [attr.y]=\"getRadarAxisYLabel(axisId)\" [attr.text-anchor]=\"getRadarAxisLabelAnchor(axisId)\">{{ getPrintRadarLabel(axisId) }}</text>",
    "              <text [attr.x]=\"getPrintRadarScoreX(axisId)\" [attr.y]=\"getPrintRadarScoreY(axisId)\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"11\" font-weight=\"700\" fill=\"#9b1c1c\">{{ getPrintRadarScore100(axisId) }}</text>",
    "            }",
    "            <polygon [attr.points]=\"getRadarPolygonPoints(getRadarValues(activeRecord))\" fill=\"rgba(155,28,28,0.15)\" stroke=\"#9b1c1c\" stroke-width=\"2\" />",
    "          </svg>",
    f"        </{D}>",
    "        <table class=\"analysis-table\" aria-label=\"分類統計表\">",
    "          <thead>",
    "            <tr>",
    "              <th>分類</th>",
    "              <th>分數</th>",
    "              <th>已確認 / 總數</th>",
    "              <th>分析重點</th>",
    "            </tr>",
    "          </thead>",
    "          <tbody>",
    "            @for (row of reportCategoryStats; track row.label) {",
    "              <tr>",
    "                <td>{{ row.label }}</td>",
    "                <td class=\"red\">{{ row.score }}</td>",
    "                <td>{{ row.confirmed }} / {{ row.total }}</td>",
    "                <td>{{ truncateForPrint(row.analysis, 28) }}</td>",
    "              </tr>",
    "            }",
    "          </tbody>",
    "        </table>",
    f"      </{D}>",
    "    </section>",
    "",
    "    <section class=\"section section--checklist\">",
    f"      <{D} class=\"section-title\"><span class=\"num\">4.</span> CHECKLIST 明細表（重點項目）</{D}>",
    f"      <{D} class=\"checklist-content\">",
    f"        <{D} class=\"checklist-grid\">",
    "          <table class=\"checklist-table\" aria-label=\"重要檢查項目左欄\">",
    "            <thead>",
    "              <tr><th>分類</th><th>檢查項目</th><th>狀態</th><th>備註</th></tr>",
    "            </thead>",
    "            <tbody>",
    "              @for (row of reportImportantChecklistCol1; track row.title) {",
    "                <tr>",
    "                  <td>{{ row.category }}</td>",
    "                  <td>{{ row.title }}</td>",
    "                  <td><span [class]=\"printStatusClass(row.status)\">{{ row.statusLabel }}</span></td>",
    "                  <td>{{ truncateForPrint(row.note, 20) }}</td>",
    "                </tr>",
    "              }",
    "            </tbody>",
    "          </table>",
    "          <table class=\"checklist-table\" aria-label=\"重要檢查項目右欄\">",
    "            <thead>",
    "              <tr><th>分類</th><th>檢查項目</th><th>狀態</th><th>備註</th></tr>",
    "            </thead>",
    "            <tbody>",
    "              @for (row of reportImportantChecklistCol2; track row.title) {",
    "                <tr>",
    "                  <td>{{ row.category }}</td>",
    "                  <td>{{ row.title }}</td>",
    "                  <td><span [class]=\"printStatusClass(row.status)\">{{ row.statusLabel }}</span></td>",
    "                  <td>{{ truncateForPrint(row.note, 20) }}</td>",
    "                </tr>",
    "              }",
    "            </tbody>",
    "          </table>",
    f"        </{D}>",
    f"      </{D}>",
    "    </section>",
    "",
    "    <section class=\"section section--bottom\">",
    f"      <{D} class=\"section-title\"><span class=\"num\">5.</span> 建議下一步 · <span class=\"num\">6.</span> 備註</{D}>",
    f"      <{D} class=\"bottom-content\">",
    f"        <{D} class=\"next-steps\">",
    "          @for (action of reportNextActionsForPrint; track action.title; let i = $index) {",
    f"            <{D} class=\"step\">",
    "              <span class=\"step-num\">{{ i + 1 }}</span>",
    f"              <{D}>",
    f"                <{D} class=\"step-title\">{{ action.title }}</{D}>",
    f"                <{D} class=\"small-text\">{{ action.description }}</{D}>",
    f"              </{D}>",
    f"            </{D}>",
    "          }",
    f"        </{D}>",
    f"        <{D} class=\"notes-box\" aria-label=\"手寫備註區\"></{D}>",
    f"      </{D}>",
    "    </section>",
    "",
    "    <footer class=\"report-footer\">",
    "      <span>Rental Buddy 看房分析報告</span>",
    "      <span>本報告由 Rental Buddy 生成，僅供參考</span>",
    "    </footer>",
    "  </section>",
]

new_block = "\n".join(new_lines) + "\n"
path.write_text(text[:start] + new_block + text[end:], encoding="utf-8")
print("patched", path)
